name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ahmed2094/supportek

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build --no-cache --force-rm -t ${{ env.IMAGE_NAME }} .

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Increment version number
        run: |
          VERSION_FILE=version.txt
          if [ -f "$VERSION_FILE" ]; then
            VERSION=$(cat $VERSION_FILE)
            VERSION=$((VERSION+1))
          else
            VERSION=1
          fi
          echo $VERSION > $VERSION_FILE
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        id: increment_version

      - name: Commit and push updated version file
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add version.txt
          git commit -m "Increment version number to ${{ env.VERSION }}"
          git push

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.VERSION }}
