name: Docker Image CI

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ahmed2094/supportek

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build and push Docker image
        run: |
          VERSION=$(date +'%Y%m%d%H%M%S')
          docker build --no-cache --force-rm -t ${{ env.IMAGE_NAME }}:$VERSION .
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push ${{ env.IMAGE_NAME }}:$VERSION
